services:
  authronom-backend-postgres:
    container_name: authronom-backend-postgres
    image: postgres:17.3
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "authronom-backend"
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgresql_init_scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  authronom-backend-redis:
    container_name: authronom-backend-redis
    image: redis:7.4.2
    command: redis-server --save 20 1 --loglevel warning --requirepass user
    ports:
      - '6379:6379'

  # Inspired by https://mailpit.axllent.org/docs/install/docker/#docker-compose-example
  mailpit:
    container_name: authronom-backend-mailpit
    image: axllent/mailpit:v1.24
    volumes:
      - type: volume
        source: mailpit-data
        target: /data
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgresql-data:
    name: authronom-backend-postgresql17-data
  mailpit-data:
    name: authronom-backend-mailpit-data
