services:
  authronom-backend-postgres:
    container_name: authronom-backend-postgres
    image: postgres:17.3
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
      POSTGRES_DB: "authronom-backend"
    ports:
      - '5435:5432'
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgresql_init_scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql

  authronom-backend-redis:
    container_name: authronom-backend-redis
    image: redis:7.4.2
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass user
    ports:
      - '6379:6379'

volumes:
  postgresql-data:
    name: authronom-backend-postgresql17-data
