services:
  authronom-backend-postgres:
    container_name: authronom-backend-postgres
    image: postgres:17.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "authronom-backend"
    ports:
      - '5432:5432'
    volumes:
      - type: volume
        source: postgresql-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgresql_init_scripts/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  authronom-backend-redis:
    container_name: authronom-backend-redis
    image: redis:7.4.3
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Inspired by https://mailpit.axllent.org/docs/install/docker/#docker-compose-example
  authronom-backend-mailpit:
    container_name: authronom-backend-mailpit
    image: axllent/mailpit:v1.24.1
    volumes:
      - type: volume
        source: mailpit-data
        target: /data
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  postgresql-data:
    name: authronom-backend-postgresql17-data
  mailpit-data:
    name: authronom-backend-mailpit-data
